// Lista centralizada dos produtos do catálogo
export const catalogProducts = [
  {
    id: 'local-xbox-series-x',
    name: 'Xbox Series X',
    description: 'Console Xbox Series X 1TB',
    price: 3999.90,
    original_price: 4499.90,
    image_url: 'https://m.media-amazon.com/images/I/516pVDAQMnL.jpg',
    category_id: 'consoles',
    stock: 5,
    rating: 4.9,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'local-playstation-5',
    name: 'PlayStation 5',
    description: 'Console Sony PlayStation 5 Slim Branco',
    price: 4299.90,
    original_price: 4799.90,
    image_url: 'https://images.kabum.com.br/produtos/fotos/527400/console-playstation-5-sony-slim-branco-2-jogos-1000038899_1710512865_gg.jpg',
    category_id: 'consoles',
    stock: 7,
    rating: 4.8,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'local-nintendo-switch',
    name: 'Nintendo Switch',
    description: 'Console Nintendo Switch Neon',
    price: 2299.90,
    original_price: 2499.90,
    image_url: 'https://m.media-amazon.com/images/I/7148mbvrbWL.jpg',
    category_id: 'consoles',
    stock: 8,
    rating: 4.7,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'local-mouse-razer-basilisk',
    name: 'Mouse Gamer Razer Basilisk',
    description: 'Mouse Gamer Razer Basilisk Ultimate',
    price: 499.90,
    original_price: 599.90,
    image_url: 'https://theawesomer.com/photos/2019/11/razer_basilisk_ultimate_mouse_4.jpg',
    category_id: 'perifericos',
    stock: 15,
    rating: 4.6,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'local-controle-xbox-series-x',
    name: 'Controle Xbox Series X',
    description: 'Controle sem fio original para Xbox Series X',
    price: 399.90,
    original_price: 449.90,
    image_url: 'https://cdn.awsli.com.br/600x450/1919/1919257/produto/120337656/d8fc9b09e0.jpg',
    category_id: 'acessorios',
    stock: 10,
    rating: 4.8,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'local-controle-ps5-dualsense',
    name: 'Controle PS5 DualSense',
    description: 'Controle sem fio DualSense para PlayStation 5',
    price: 349.90,
    original_price: 399.90,
    image_url: 'https://images.kabum.com.br/produtos/fotos/115801/controle-sem-fio-ps5-dualsense_1598897393_gg.jpg',
    category_id: 'acessorios',
    stock: 12,
    rating: 4.7,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'local-cadeira-gamer-rgb-draxen',
    name: 'Cadeira Gamer RGB Draxen',
    description: 'Cadeira gamer com iluminação RGB Draxen',
    price: 1299.90,
    original_price: 1499.90,
    image_url: 'https://cdn.dooca.store/1841/products/cadeira-rgb-draxen.jpg?v=1644257662&webp=0',
    category_id: 'cadeiras',
    stock: 6,
    rating: 4.5,
    featured: false,
    created_at: new Date().toISOString(),
  },
];
